# -*- coding: utf-8 -*-
"""Project 08

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BoU5EmWMuYhB68XwMo7p-aelurZLN-S0
"""

"""
NumPy Analyzer
==============
A menu-driven console toolkit that combines NumPy functionality with
Object-Oriented Programming principles (encapsulation, class methods,
static methods, constructors).

Run with:  python numpy_analyzer.py
"""

import numpy as np


class DataAnalytics:
    """
    Encapsulates array creation, manipulation, math operations,
    searching/sorting/filtering, and statistical analysis using NumPy.
    """

    # ------------------------------------------------------------------
    # Constructor
    # ------------------------------------------------------------------
    def __init__(self, array=None):
        # "Private" attribute (name-mangled) -> encapsulation
        self.__array = np.array(array) if array is not None else None

    # ------------------------------------------------------------------
    # Encapsulation: controlled access to the private array
    # ------------------------------------------------------------------
    @property
    def array(self):
        return self.__array

    @array.setter
    def array(self, new_array):
        self.__array = np.array(new_array)

    def __check_array(self):
        """Private helper: raise an error if no array exists yet."""
        if self.__array is None:
            raise ValueError("No array has been created yet.")

    # ------------------------------------------------------------------
    # 1. Array Creation
    # ------------------------------------------------------------------
    @classmethod
    def create_from_input(cls, dimensions, shape, elements):
        """
        Class method: builds a DataAnalytics instance from raw input.
        dimensions: 1, 2, or 3
        shape: tuple describing the shape, e.g. (6,), (2,3), (2,2,2)
        elements: flat list of numbers
        """
        arr = np.array(elements).reshape(shape)
        return cls(arr)

    # ------------------------------------------------------------------
    # 2. Indexing & Slicing
    # ------------------------------------------------------------------
    def index_element(self, indices):
        self.__check_array()
        return self.__array[indices]

    def slice_array(self, row_slice, col_slice=None):
        self.__check_array()
        if col_slice is None:
            return self.__array[row_slice]
        return self.__array[row_slice, col_slice]

    # ------------------------------------------------------------------
    # 3. Combining & Splitting
    # ------------------------------------------------------------------
    def combine(self, other_array, axis=0):
        self.__check_array()
        return np.concatenate((self.__array, other_array), axis=axis)

    def split(self, num_splits, axis=0):
        self.__check_array()
        return np.array_split(self.__array, num_splits, axis=axis)

    # ------------------------------------------------------------------
    # 4. Mathematical Operations
    # ------------------------------------------------------------------
    def add(self, other):
        return self.__elementwise(other, "+")

    def subtract(self, other):
        return self.__elementwise(other, "-")

    def multiply(self, other):
        return self.__elementwise(other, "*")

    def divide(self, other):
        return self.__elementwise(other, "/")

    def __elementwise(self, other, op):
        """Private helper for element-wise math operations."""
        self.__check_array()
        other = np.array(other)
        if op == "+":
            return self.__array + other
        elif op == "-":
            return self.__array - other
        elif op == "*":
            return self.__array * other
        elif op == "/":
            return self.__array / other

    def dot_product(self, other):
        self.__check_array()
        return np.dot(self.__array, np.array(other))

    def matrix_multiply(self, other):
        self.__check_array()
        return np.matmul(self.__array, np.array(other))

    # ------------------------------------------------------------------
    # 5. Search, Sort, Filter
    # ------------------------------------------------------------------
    def search(self, value):
        self.__check_array()
        return np.argwhere(self.__array == value)

    def sort(self, ascending=True, axis=-1):
        self.__check_array()
        sorted_arr = np.sort(self.__array, axis=axis)
        if not ascending:
            sorted_arr = np.flip(sorted_arr, axis=axis)
        return sorted_arr

    def filter_values(self, condition_func):
        self.__check_array()
        return self.__array[condition_func(self.__array)]

    # ------------------------------------------------------------------
    # 6. Aggregating Functions
    # ------------------------------------------------------------------
    def sum(self):
        self.__check_array()
        return np.sum(self.__array)

    def mean(self):
        self.__check_array()
        return np.mean(self.__array)

    def median(self):
        self.__check_array()
        return np.median(self.__array)

    def std_dev(self):
        self.__check_array()
        return np.std(self.__array)

    def variance(self):
        self.__check_array()
        return np.var(self.__array)

    # ------------------------------------------------------------------
    # 7. Statistical Functions
    # ------------------------------------------------------------------
    def min_max(self):
        self.__check_array()
        return np.min(self.__array), np.max(self.__array)

    def percentile(self, q):
        self.__check_array()
        return np.percentile(self.__array, q)

    def correlation(self, other):
        self.__check_array()
        other = np.array(other)
        return np.corrcoef(self.__array.flatten(), other.flatten())[0, 1]

    # ------------------------------------------------------------------
    # Static utility method
    # ------------------------------------------------------------------
    @staticmethod
    def get_int_input(prompt):
        """Static method: safely read an integer from the user."""
        while True:
            try:
                return int(input(prompt))
            except ValueError:
                print("Invalid number, please try again.")

    def __str__(self):
        self.__check_array()
        return str(self.__array)


# ==========================================================================
# Helper functions for the menu-driven console UI
# ==========================================================================

def read_elements(count, prompt):
    """Read `count` numeric elements typed on one line separated by spaces."""
    while True:
        raw = input(prompt).split()
        if len(raw) != count:
            print(f"Please enter exactly {count} elements.")
            continue
        try:
            return [float(x) if "." in x else int(x) for x in raw]
        except ValueError:
            print("Invalid input, numbers only.")


def create_array_menu():
    print("\nSelect the type of array to create:")
    print("1. 1D Array")
    print("2. 2D Array")
    print("3. 3D Array")
    choice = DataAnalytics.get_int_input("Enter your choice: ")

    if choice == 1:
        n = DataAnalytics.get_int_input("Enter the number of elements: ")
        elements = read_elements(n, f"Enter {n} elements for the array separated by space: ")
        da = DataAnalytics.create_from_input(1, (n,), elements)

    elif choice == 2:
        rows = DataAnalytics.get_int_input("Enter the number of rows: ")
        cols = DataAnalytics.get_int_input("Enter the number of columns: ")
        n = rows * cols
        elements = read_elements(n, f"Enter {n} elements for the array separated by space: ")
        da = DataAnalytics.create_from_input(2, (rows, cols), elements)

    elif choice == 3:
        d1 = DataAnalytics.get_int_input("Enter size of dimension 1: ")
        d2 = DataAnalytics.get_int_input("Enter size of dimension 2: ")
        d3 = DataAnalytics.get_int_input("Enter size of dimension 3: ")
        n = d1 * d2 * d3
        elements = read_elements(n, f"Enter {n} elements for the array separated by space: ")
        da = DataAnalytics.create_from_input(3, (d1, d2, d3), elements)

    else:
        print("Invalid choice.")
        return None

    print("\nArray created successfully:")
    print(da)
    return da


def indexing_slicing_menu(da):
    while True:
        print("\nChoose an operation:")
        print("1. Indexing")
        print("2. Slicing")
        print("3. Go Back")
        choice = DataAnalytics.get_int_input("Enter your choice: ")

        if choice == 1:
            idx_str = input("Enter index (comma separated, e.g. 0,1): ")
            idx = tuple(int(i) for i in idx_str.split(","))
            print("Element:", da.index_element(idx))

        elif choice == 2:
            row_range = input("Enter the row range (start:end): ")
            r_start, r_end = (int(x) for x in row_range.split(":"))
            if da.array.ndim > 1:
                col_range = input("Enter the column range (start:end): ")
                c_start, c_end = (int(x) for x in col_range.split(":"))
                result = da.slice_array(slice(r_start, r_end), slice(c_start, c_end))
            else:
                result = da.slice_array(slice(r_start, r_end))
            print("\nSliced Array:")
            print(result)

        elif choice == 3:
            break
        else:
            print("Invalid choice.")


def math_operations_menu(da):
    print("\nChoose a mathematical operation:")
    print("1. Addition")
    print("2. Subtraction")
    print("3. Multiplication")
    print("4. Division")
    print("5. Dot Product")
    print("6. Matrix Multiplication")
    choice = DataAnalytics.get_int_input("Enter your choice: ")

    size = da.array.size
    shape = da.array.shape
    elements = read_elements(size, f"Enter the same-size array elements ({size} elements separated by space): ")
    other = np.array(elements).reshape(shape)

    print("\nOriginal Array:")
    print(da)
    print("\nSecond Array:")
    print(other)

    if choice == 1:
        print("\nResult of Addition:")
        print(da.add(other))
    elif choice == 2:
        print("\nResult of Subtraction:")
        print(da.subtract(other))
    elif choice == 3:
        print("\nResult of Multiplication:")
        print(da.multiply(other))
    elif choice == 4:
        print("\nResult of Division:")
        print(da.divide(other))
    elif choice == 5:
        print("\nDot Product:")
        print(da.dot_product(other))
    elif choice == 6:
        print("\nMatrix Multiplication:")
        print(da.matrix_multiply(other))
    else:
        print("Invalid choice.")


def combine_split_menu(da):
    print("\nChoose an option:")
    print("1. Combine Arrays")
    print("2. Split Array")
    choice = DataAnalytics.get_int_input("Enter your choice: ")

    if choice == 1:
        size = da.array.size
        elements = read_elements(size, f"Enter the elements of another array to combine ({size} elements separated by space): ")
        other = np.array(elements).reshape(da.array.shape)
        print("\nOriginal Array:")
        print(da)
        print("\nSecond Array:")
        print(other)
        print("\nCombined Array (Vertical Stack):")
        print(da.combine(other, axis=0))

    elif choice == 2:
        n = DataAnalytics.get_int_input("Enter the number of splits: ")
        parts = da.split(n)
        print("\nSplit Arrays:")
        for i, p in enumerate(parts, 1):
            print(f"Part {i}:")
            print(p)
    else:
        print("Invalid choice.")


def search_sort_filter_menu(da):
    print("\nChoose an option:")
    print("1. Search a value")
    print("2. Sort the array")
    print("3. Filter values")
    choice = DataAnalytics.get_int_input("Enter your choice: ")

    print("\nOriginal Array:")
    print(da)

    if choice == 1:
        value = float(input("Enter the value to search for: "))
        result = da.search(value)
        print("\nValue found at indices:" if result.size else "\nValue not found.")
        if result.size:
            print(result)

    elif choice == 2:
        order = input("Sort ascending or descending? (a/d): ").strip().lower()
        sorted_arr = da.sort(ascending=(order != "d"))
        print("\nSorted Array:")
        print(sorted_arr)
        print("(Sorting applied row-wise.)")

    elif choice == 3:
        op = input("Filter condition (>, <, >=, <=, ==): ").strip()
        val = float(input("Value to compare against: "))
        conditions = {
            ">": lambda a: a > val,
            "<": lambda a: a < val,
            ">=": lambda a: a >= val,
            "<=": lambda a: a <= val,
            "==": lambda a: a == val,
        }
        if op in conditions:
            print("\nFiltered Values:")
            print(da.filter_values(conditions[op]))
        else:
            print("Invalid condition.")
    else:
        print("Invalid choice.")


def aggregates_stats_menu(da):
    print("\nChoose an aggregate/statistical operation:")
    print("1. Sum")
    print("2. Mean")
    print("3. Median")
    print("4. Standard Deviation")
    print("5. Variance")
    print("6. Min and Max")
    print("7. Percentile")
    print("8. Correlation with another array")
    choice = DataAnalytics.get_int_input("Enter your choice: ")

    print("\nOriginal Array:")
    print(da)

    if choice == 1:
        print("\nSum of Array:", da.sum())
    elif choice == 2:
        print("\nMean of Array:", da.mean())
    elif choice == 3:
        print("\nMedian of Array:", da.median())
    elif choice == 4:
        print("\nStandard Deviation of Array:", da.std_dev())
    elif choice == 5:
        print("\nVariance of Array:", da.variance())
    elif choice == 6:
        mn, mx = da.min_max()
        print(f"\nMin: {mn}, Max: {mx}")
    elif choice == 7:
        q = float(input("Enter percentile (0-100): "))
        print(f"\n{q}th Percentile:", da.percentile(q))
    elif choice == 8:
        size = da.array.size
        elements = read_elements(size, f"Enter {size} elements for comparison array: ")
        other = np.array(elements).reshape(da.array.shape)
        print("\nCorrelation Coefficient:", da.correlation(other))
    else:
        print("Invalid choice.")


# ==========================================================================
# Main program loop
# ==========================================================================

def main():
    print("Welcome to the NumPy Analyzer!")
    print("=" * 40)

    da = None

    while True:
        print("\nChoose an option:")
        print("1. Create a Numpy Array")
        print("2. Perform Mathematical Operations")
        print("3. Combine or Split Arrays")
        print("4. Search, Sort, or Filter Arrays")
        print("5. Compute Aggregates and Statistics")
        print("6. Exit")
        choice = DataAnalytics.get_int_input("Enter your choice: ")

        if choice == 1:
            new_da = create_array_menu()
            if new_da is not None:
                da = new_da
                indexing_slicing_menu(da)

        elif choice in (2, 3, 4, 5) and da is None:
            print("\nPlease create an array first (Option 1).")

        elif choice == 2:
            math_operations_menu(da)

        elif choice == 3:
            combine_split_menu(da)

        elif choice == 4:
            search_sort_filter_menu(da)

        elif choice == 5:
            aggregates_stats_menu(da)

        elif choice == 6:
            print("\nThank you for using the NumPy Analyzer!")
            print("Goodbye!")
            break

        else:
            print("Invalid choice, please try again.")


if __name__ == "__main__":
    main()